version: '3.8'

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: time_manager_prod
      MIX_ENV: prod
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  time_manager:
    build:
      context: ./time_manager
      dockerfile: Dockerfile.prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: time_manager_prod
      DATABASE_URL: ecto://postgres:postgres@db/time_manager_prod
      MIX_ENV: prod
      PORT: 4000
      SECRET_KEY_BASE: your_secret_key_base
    ports:
      - "4000:4000"
    depends_on:
      - db

  # vuejs:
  #   build:
  #     context: ./front-end
  #     dockerfile: Dockerfile.prod
  #   environment:
  #     API_ENDPOINT: http://time_manager:4000/api
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - time_manager

volumes:
  pgdata:
