services:
  elixir:
    build: 
      dockerfile: Dockerfile.dev
      context: ./time_manager
    ports:
      - "4000:4000"
    # supprime le service elixir si tu galères
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: time_manager_dev
      MIX_ENV: dev
    volumes:
      - './time_manager:/time_manager' # Monter le dossier de travail pour avoir le hot-reloading
      - '/time_manager/deps' # Monter les dépendances pour éviter les conflits avec le conteneur
      - '/time_manager/_build' # Monter le dossier de build pour le caching
  db:
    image: 'postgres:11-alpine'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: time_manager_dev
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  vuejs:
    build: 
        context: ./front-end
        dockerfile: Dockerfile
    ports:
      - '8000:5173'
    volumes:
      - './front-end:/front-end'
      - /front-end/node_modules
volumes:
  pgdata: