services:
  elixir:
    build:
      dockerfile: Dockerfile.prod
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER_PROD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PROD}
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB_PROD}
      MIX_ENV: prod
      PORT: 4000
      DATABASE_URL: ${DATABASE_URL_PROD}
      SECRET_KEY_BASE: QwaH+0XnSp1qJGEAHWvVH3lu2AbxpH8UmkFQ7CiZNlkUhoKGGkHREOLNGmMV+0M3
    volumes:
      - './backend:/backend'
  db:
    image: 'postgres:11-alpine'
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_PROD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PROD}
      POSTGRES_DB: ${POSTGRES_DB_PROD}
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

  vuejs:
    build:
      context: ./front-end
      dockerfile: Dockerfile.prod
    ports:
      - '8000:8000'
      # - '8080:5173'
    volumes:
      - './front-end:/front-end'
      - /front-end/node_modules
volumes:
  pgdata:
