FROM bitwalker/alpine-elixir-phoenix:latest

# # Copier tout le contenu du dossier time_manager dans le conteneur
COPY . /backend
# Définir le répertoire de travail
WORKDIR /backend

# RUN mix deps.get

# Rendre le script entrypoint.sh exécutable
RUN chmod +x ./entrypoint.dev.sh

# Installer les utilitaires PostgreSQL pour pg_isready (si nécessaire)
RUN apk --no-cache add postgresql-client

# Exécuter le script entrypoint.sh avec sh
CMD ["sh", "./entrypoint.dev.sh"]
